/**
 * lib/seo/fetch-rendered.ts
 * ─────────────────────────────────────────────────────────────────────────
 * Fetch one of our own pages and read the things only the rendered HTML
 * knows: the canonical, the hreflang set, how many H1s there are, what
 * JSON-LD was emitted, what the robots meta says, and how much text and how
 * many un-alt'd images a reader actually gets.
 *
 * WHY THE DATABASE CANNOT ANSWER THESE
 *
 * A translation row can exist while the hreflang tag is missing, and it is
 * the tag Google reads. The canonical comes from metadata that several
 * pages override. The H1 count depends on the layout as well as the body —
 * see lib/heading-policy.ts, which strips the body's first H1 precisely so
 * the total comes out at one. Auditing the row would audit our intentions;
 * auditing the page audits what was served.
 *
 * PARSED WITH REGULAR EXPRESSIONS, ON PURPOSE
 *
 * The alternative is a DOM parser, which means a dependency for a job that
 * reads six specific tags out of our own markup. The risk a regex parser
 * normally carries — malformed or hostile HTML — does not apply: this
 * fetches its own site, where the markup is generated by Next from
 * sanitized content. The one place that matters, the visible word count,
 * strips tags rather than trying to understand them.
 *
 * FAILURE IS "SKIP", NEVER "FAIL"
 *
 * Every caller gets null when the page could not be fetched, and every rule
 * that reads it skips. "We could not look" and "we looked and it was wrong"
 * are different answers, and scoring the first as the second would light up
 * the whole board the first time the site was briefly slow.
 * ─────────────────────────────────────────────────────────────────────────
 */

import "server-only";
import type { RenderedPage } from "@/lib/seo/types";

/** Long enough for a cold ISR render, short enough that a few hundred of
 *  them cannot run all night. */
const TIMEOUT_MS = 15_000;

export async function fetchRendered(url: string): Promise<RenderedPage | null> {
  try {
    const response = await fetch(url, {
      // The audit must see what a visitor sees, not a cached copy of what
      // the page looked like before the edit being audited.
      cache: "no-store",
      redirect: "follow",
      signal: AbortSignal.timeout(TIMEOUT_MS),
      headers: {
        // Identifies the crawler in our own access logs, so a spike is
        // attributable rather than mysterious.
        "User-Agent": "AndamanSeoAudit/1.0 (+self-audit)",
      },
    });

    if (!response.ok) return null;

    return parseRendered(await response.text());
  } catch {
    // Timeout, DNS, a connection reset. All of them mean "could not look".
    return null;
  }
}

/**
 * Exported for its test — the parsing is the part with edge cases, and it
 * needs no network to exercise.
 */
export function parseRendered(html: string): RenderedPage {
  return {
    canonical: firstMatch(html, /<link[^>]+rel=["']canonical["'][^>]*>/i, (tag) => attr(tag, "href")),
    hreflang: [...html.matchAll(/<link[^>]+hreflang=["']([^"']+)["'][^>]*>/gi)].map((m) =>
      m[1].toLowerCase(),
    ),
    h1Count: [...html.matchAll(/<h1\b[^>]*>/gi)].length,
    jsonLdTypes: jsonLdTypes(html),
    metaRobots: firstMatch(
      html,
      /<meta[^>]+name=["']robots["'][^>]*>/i,
      (tag) => attr(tag, "content")?.toLowerCase() ?? null,
    ),
    ...imageStats(html),
    wordCount: visibleWordCount(html),
  };
}

function firstMatch<T>(html: string, pattern: RegExp, read: (tag: string) => T | null): T | null {
  const match = html.match(pattern);
  return match ? read(match[0]) : null;
}

function attr(tag: string, name: string): string | null {
  const match = tag.match(new RegExp(`${name}=["']([^"']*)["']`, "i"));
  return match ? match[1] : null;
}

/**
 * Every @type in every ld+json block, flattened.
 *
 * A block can be an object, an array of them, or a @graph — all three
 * appear on this site (see lib/article-schema.ts, which returns an array).
 * A block that does not parse is skipped rather than throwing: one broken
 * script must not make the whole page unauditable.
 */
function jsonLdTypes(html: string): string[] {
  const types: string[] = [];

  for (const match of html.matchAll(
    /<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi,
  )) {
    try {
      collectTypes(JSON.parse(match[1]), types);
    } catch {
      // Not valid JSON. Nothing to collect, and not this function's
      // problem to report.
    }
  }

  return types;
}

function collectTypes(node: unknown, into: string[]): void {
  if (Array.isArray(node)) {
    for (const item of node) collectTypes(item, into);
    return;
  }
  if (!node || typeof node !== "object") return;

  const record = node as Record<string, unknown>;
  const type = record["@type"];
  if (typeof type === "string") into.push(type);
  else if (Array.isArray(type)) for (const t of type) if (typeof t === "string") into.push(t);

  if (record["@graph"]) collectTypes(record["@graph"], into);
}

/**
 * Images a reader is meant to perceive, and how many of those carry no alt.
 *
 * Decorative images are excluded entirely — not counted as missing, and not
 * counted in the total. An `<img alt="" aria-hidden="true">` is the correct
 * markup for something a screen reader should skip, and the language
 * switcher's flag icon is exactly that on every page of the site.
 *
 * The first version counted them, and every one of the 80 URLs failed this
 * rule because of one flag icon in the header. A rule that fails everything
 * is a rule people learn to scroll past, which costs more than the rule was
 * ever worth — and it would have buried the finding underneath it, which is
 * real: the sales-team photographs on /contact carry alt="" with no
 * aria-hidden, so they are content images announced as decoration.
 */
function imageStats(html: string): { imageCount: number; imagesMissingAlt: number } {
  const tags = [...html.matchAll(/<img\b[^>]*>/gi)]
    .map((m) => m[0])
    .filter((tag) => !isDecorative(tag));

  const missing = tags.filter((tag) => (attr(tag, "alt") ?? "").trim().length === 0).length;

  return { imageCount: tags.length, imagesMissingAlt: missing };
}

/** Marked as "skip me" for assistive technology, which is a deliberate
 *  decision and not an omission. */
function isDecorative(tag: string): boolean {
  return (
    attr(tag, "aria-hidden")?.toLowerCase() === "true" ||
    attr(tag, "role")?.toLowerCase() === "presentation" ||
    attr(tag, "role")?.toLowerCase() === "none"
  );
}

/**
 * Words a reader actually sees.
 *
 * script and style are removed whole — their contents are not prose, and
 * counting a JSON-LD block as body text would make every page look
 * substantial. Everything else is stripped to its text.
 *
 * Whitespace-separated, which undercounts Thai: Thai does not space its
 * words. That is a known limitation of a 300-word threshold on a bilingual
 * site, and it fails in the safe direction — a Thai page reads as thinner
 * than it is, which prompts a look rather than hiding one.
 */
function visibleWordCount(html: string): number {
  const text = html
    .replace(/<script[\s\S]*?<\/script>/gi, " ")
    .replace(/<style[\s\S]*?<\/style>/gi, " ")
    .replace(/<[^>]+>/g, " ")
    .replace(/&[a-z]+;|&#\d+;/gi, " ")
    .replace(/\s+/g, " ")
    .trim();

  return text.length === 0 ? 0 : text.split(" ").length;
}
