/**
 * lib/news-leads.ts
 * ─────────────────────────────────────────────────────────────────────────
 * "Leads generated" per article, for /admin/news.
 *
 * There is no schema link between LeadInquiry and NewsArticle — adding one
 * would need a migration, and there is a schema-free way to answer the
 * same question honestly: the article page's only lead-capture link (see
 * the CTA in app/[locale]/(site)/news/[slug]/page.tsx) tags itself
 * `utm_medium=article&utm_campaign=<slug>`, and LeadForm
 * (components/LeadForm.tsx) already copies whatever utm_* params are on
 * the URL onto the lead it creates. So "leads generated by this article"
 * is exactly "LeadInquiry rows with utmMedium='article' and utmCampaign
 * equal to this slug" — no new column, just reading the attribution this
 * project already collects.
 *
 * This undercounts on purpose rather than overcounting: a visitor who
 * reads the article, then finds the contact page some other way (search,
 * the main nav) minutes later, submits with no utm_campaign and is not
 * counted here — correctly, since nothing links that submission back to
 * this article once the query string is gone.
 */

import { prisma } from "@/lib/prisma";
import { safeQuery } from "@/lib/db";

const ARTICLE_UTM_MEDIUM = "article";

/** slug -> number of leads whose utm_campaign named that article. */
export async function getLeadCountsByArticleSlug(
  slugs: string[],
): Promise<Map<string, number>> {
  if (slugs.length === 0) return new Map();

  const rows = await safeQuery(
    "leadInquiry.groupBy(byArticleSlug)",
    () =>
      prisma.leadInquiry.groupBy({
        by: ["utmCampaign"],
        where: {
          utmMedium: ARTICLE_UTM_MEDIUM,
          utmCampaign: { in: slugs },
        },
        _count: { _all: true },
      }),
    [] as { utmCampaign: string | null; _count: { _all: number } }[],
  );

  const counts = new Map<string, number>();
  for (const row of rows) {
    if (row.utmCampaign) counts.set(row.utmCampaign, row._count._all);
  }
  return counts;
}
